// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp-oMb4-bRp_0Zq9qj9Hlr-Mkh0AC6oJI',
    appId: '1:175660479428:web:3c191af1294c9db9b7aa91',
    messagingSenderId: '175660479428',
    projectId: 'mbnc-84d53',
    authDomain: 'mbnc-84d53.firebaseapp.com',
    storageBucket: 'mbnc-84d53.firebasestorage.app',
    measurementId: 'G-YPJSCM9DJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk7fs3NZK1oS3ufzSjGgpKv7SXQMM1JGQ',
    appId: '1:175660479428:android:c50f590211142785b7aa91',
    messagingSenderId: '175660479428',
    projectId: 'mbnc-84d53',
    storageBucket: 'mbnc-84d53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe118yyjC13q_WjdufICqGkA1zzgFXR4c',
    appId: '1:175660479428:ios:e02c7c859b2183d6b7aa91',
    messagingSenderId: '175660479428',
    projectId: 'mbnc-84d53',
    storageBucket: 'mbnc-84d53.firebasestorage.app',
    iosBundleId: 'com.phuongquynh1112.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe118yyjC13q_WjdufICqGkA1zzgFXR4c',
    appId: '1:175660479428:ios:f8f534ce8d8a0e89b7aa91',
    messagingSenderId: '175660479428',
    projectId: 'mbnc-84d53',
    storageBucket: 'mbnc-84d53.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp-oMb4-bRp_0Zq9qj9Hlr-Mkh0AC6oJI',
    appId: '1:175660479428:web:0a66b1454e40f555b7aa91',
    messagingSenderId: '175660479428',
    projectId: 'mbnc-84d53',
    authDomain: 'mbnc-84d53.firebaseapp.com',
    storageBucket: 'mbnc-84d53.firebasestorage.app',
    measurementId: 'G-46L6F5HZCT',
  );
}
